# Generated by Django 3.0 on 2021-07-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('these', '0003_auto_20210630_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='these',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='these',
            name='objectif',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='these',
            name='results',
            field=models.CharField(default='', max_length=500),
        ),
    ]
