# Generated by Django 3.0 on 2021-07-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('these', '0004_auto_20210701_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='these',
            name='description',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='these',
            name='objectif',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='these',
            name='results',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
